name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Manual step
        run: |
          echo "Hello World from Manual Worksflow."
          echo "Hello Bangladesh from Manual Worksflow."