name: Cron Job Workflow
on:
  schedule:
    - cron: '*/2 * * * *'  # This cron expression runs the job every 5 minutes
jobs: 
  cron-job-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cron job step
        run: |
          echo "Hello World from Cron Job Workflow."
          echo "Hello Bangladesh from Cron Job Workflow."
          echo "This job runs automatically based on the schedule defined in the workflow."