name: Multi Job Workflow

on:
  push:
    branches:
      - main

jobs:
  first-job-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |
          echo "Hello World from Multi Job Workflow."
          echo "This job runs on every push to the main branch."

  second-job-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Second step
        run: |
          echo "Hello World from Multi Job Workflow."
          echo "This job runs on every push to the main branch."
